### ISSUE TITLE
 fabric-ca request register failed with errors

### ISSUE THREAD

**Issue by akashchekka** [IBM-Blockchain-Archive/ibm-container-service#91] opened 2018-05-15 05:42 UTC
![screenshot from 2018-05-15 11-09-49](https://user-images.githubusercontent.com/29705984/40038591-9abdc7b8-5830-11e8-82a5-6d5416ff94ca.png)
I am trying to create participant cards in playground...But it is saying error and message is authorization failure...please help me resolving this

**Comment by lesleyannjordan** [comment] 2018-05-30 16:46
@Akash76 please confirm version of composer your are using and steps executed.

**Comment by mrshah-at-ibm** [comment] 2018-07-03 18:15
@Akash76 any updates? if you resolved it, can I close this issue?

**Comment by David-Kim-TPE** [comment] 2018-08-17 09:42
![image](https://user-images.githubusercontent.com/10493277/44259675-cfa56900-a244-11e8-856b-91a4eb23a7ca.png)

Any suggestions?

I met this while I'm issuing identities using the rest api.

**Comment by davidkel** [comment] 2018-08-23 10:23
For these types of errors you need to look at the fabric-ca logs to see what is going on. For example are you using the wrong certificate than the one registered for that user name when trying to issue an identity ? Have you reached enrollment limit (composer enforces that all it's identities registered with the ca server can only be enrolled once). 
Also if you have restarted your ca server then I believe any identities registered in it are lost, for example the admin identity you have for issuing identities will now not be valid if the ca server had been restarted.
But only way to find out is to look at the CA logs.

**Comment by jpdias92** [comment] 2018-08-23 16:32
Hi everyone,

I'm facing exactly the same problem, trying to issue new identities using the admin card, either on playground, CLI or REST, always returns that Authorization failure. 

I've already tried countless variations of deleting the cards, deleting the .composer directory, starting and restaring the network while removing and reimporting the admin card...

Other than issuing identities, I can do everything else with this admin card, ping the network, add assets, add participants, add transactions connect to the network on playground using this identity.

I've looked to the log of the CA but had no luck deciphering those logs... I'll paste them here, maybe someone will know where is the problem... The file only contains logs for the startup process, the addition of the admin card and then the request to issue a new identity.

[ca_log.txt](https://github.com/IBM-Blockchain/ibm-container-service/files/2315335/ca_log.txt)

I'm using Composer v0.20.0 and Fabric, 1.2.

Thanks!

**Comment by davidkel** [comment] 2018-08-23 16:42
@jpdias92 In your specific case these lines are important
```
2018/08/23 16:13:35 [DEBUG] Received registration request from : { Name:emel Type:client Secret:**** MaxEnrollments:1 Affiliation:org1 Attributes:[] CAName:ca.org1.example.com  }
2018/08/23 16:13:35 [INFO] 172.28.0.1:42372 POST /api/v1/register 401 30 "Certificate not found with AKI '19ab65abbb04807dad12e4c0a9aaa6649e70868e3abd0217a322d89e47e1a6ae' and serial '74e4f3fb74215e3463806042656a94e4a127c419'"
```
The first line says you are trying to register an identity with a name of 'emel'. The next line says that the identity you used to request this was not known to the CA server. This is probably because you have restarted the CA server but tried to use an issuer identity (probably admin) you had got previously and it is not recognised anymore.

**Comment by jpdias92** [comment] 2018-08-23 17:13
@davidkel Thanks for you quick reply.

Maybe there is some problem on the network setup script that I'm using...

These are the steps that I'm following (on a bash script) each time I start the business network:

```
1. stopFabric.sh
2. startFabric.sh

3. composer archive create -t dir -n .
4. composer network install --card PeerAdmin@hlfv1 --archiveFile acme@0.0.1.bna

5. composer network start --networkName acme --networkVersion 0.0.1 --networkAdmin admin --networkAdminEnrollSecret adminpw --card PeerAdmin@hlfv1 --file networkadmin.card

6. rm -r ~/.composer/cards/admin@acme
7. composer card import --file networkadmin.card

8. composer network ping --card admin@acme
```

Per my understanding, when I start fabric, a new CA container comes up but I only create and import the admin card after the CA container is up. I even remove the old admin card before importing the new one so I should not have the problem you suggested...

Another thing that I find strange is that the AKI and the serial on that message are always the same on the CA log, between multiple start/stops of the network and even on the computer of a co-worker, running a different version of our business network, he also has the exact same AKI and serial, althought we only share the source code on our repo, never  those other files generated by composer like .card or .bna.

**Comment by davidkel** [comment] 2018-08-23 18:08
@jpdias92 If they are always the same then the question is how you are trying to register a new user on the CA Server, are you using the right identity ?

**Comment by jpdias92** [comment] 2018-08-24 16:42
@davidkel Besides trying when I'm connected as admin to the business network on Composer playground, I also tried via CLI with the following command:

`composer identity issue -c admin@acme -f emel.card -u emel -a resource:org.acme.Institution#9204`

It always returns the same authorization error...

I followed again the dev tutorial to create a new network and on that one I was able to issue identities with no problem, following exactly the same steps. 

However, on an unrelated project that I implemented a few months ago, I'm also having the same problem issuing the identity. I really can't see where the problem could be... My next approach will probably be to start a fresh network and move all the code from the old to the new network, it's a nasty solution but I'm out of ideas...

**Comment by davidkel** [comment] 2018-08-25 06:55
Ok so based on the fact that you are trying to use admin@acme to issue the identity and the fact the information about the identity being used on the CA Server never changes means that although you think you are using a new admin enrolled when you start the network, you actually aren't. 
Looking at your script the problem is this step
```
6. rm -r ~/.composer/cards/admin@acme
```
This is not a good way to remove a card (because in fact it won't remove the identity for that card). So what happens is you remove some card information and put some new info in (with a user and secret) but because the identity still remains for that card composer doesn't enroll the new user again as it thinks it has already done so
The only safe way to remove a card from the card store is to use
```
composer card delete -c admin@acme
```

**Comment by jpdias92** [comment] 2018-08-27 10:00
@davidkel 
Really well spotted, the problem was exactly that! Now I'm deleting the card at the beginning of the script using `composer card delete -c admin@acme` and everything works as it should.

Thanks a lot for your help and your time.

**Comment by akashchekka** [comment] 2018-09-08 16:53
I resolved issue by deleting peerAdminCard and networkAdmin card after stopping the network. Next time when i started the network with new peerAdminCard and NetworkAdmin card, i am able to create cards for the participants

**Closed as completed** 2018-09-08 16:54 UTC
Labels: composer

**Comment by ghost** [comment] 2019-05-13 08:35
@Akash76  Can you tell me that how to delete peerAdminCard and networkAdmin card after stopping the network? I have this issue when I register a new user by sdk for go.

**Comment by FatfoutiAsma** [comment] 2020-02-05 21:11
Hi, i have facing the same problem few minutes ago with hyperledger composer when trying to issue identity to my participant. In fact, i won't to restart the work from beginning (i mean deleting the admin card and then creating another one), so i just create a new participant and then things work fine when issuing the identity to it.

**Comment by prakash204** [comment] 2021-06-28 12:57
Failed to register the username NpPharma for organization Manufacturer with::fabric-ca request register failed with errors [[ { code: 71, message: 'Authorization failure' } ]]

username is NpPharma
organization is Manufacturer

got this error while trying to registering , any idea ?please let me know
